# Site settings
title: 'bulch'
email: 'bulch@bulch.ru'
description: 'Фронтенд и веб-разработка'
them_color: '#4A4A4A'
url: 'https://bulch.ru'
github_username:  'bulch'

# Build settings
markdown: kramdown
permalink: /:title
